name: Java Build and Deploy (Self-Hosted)

on:
  push:
    branches:
      - master  # Trigger on push to the main branch
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your server as the runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Build the project using Maven
    - name: Build with Maven
      run: mvn clean package

    # Step 3: Deploy the JAR locally
    - name: Deploy Application
      run: |
        mkdir -p ~/app
        cp target/*.jar ~/app/
        nohup java -jar ~/app/*.jar > ~/app/app.log 2>&1 &
